name: ttxplorer
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^1.2.1
  google_maps_flutter: ^2.2.0
  get: ^4.3.8
  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  flutter_map: ^3.1.0
  latlng: any
  image_picker: ^0.8.7
  linkedin_login: ^2.2.1
  font_awesome_flutter: ^10.4.0
  carousel_slider: ^4.0.0
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  prompt_dialog: ^1.0.0
  firebase_database: ^10.1.1
  firebase_storage: ^11.0.10
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dependency_overrides:
  firebase_messaging_platform_interface: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  hive_generator: ^1.1.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
  fonts:
  - family: RobotoSlab
    fonts:
      - asset: assets/fonts/static/RobotoSlab-Bold.ttf
