// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEbNTXzXaC0B59UK-7Q2eeGuKo-6r8RpY',
    appId: '1:874965142590:web:0284c763afb6c79c8a956f',
    messagingSenderId: '874965142590',
    projectId: 'titixplorerdb',
    authDomain: 'titixplorerdb.firebaseapp.com',
    databaseURL: 'https://titixplorerdb-default-rtdb.firebaseio.com',
    storageBucket: 'titixplorerdb.appspot.com',
    measurementId: 'G-689D9WTCTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8kQa6ANmXmpL0DVJOzvK0jzONO0LgnFU',
    appId: '1:874965142590:android:abb3e1894ba86b2c8a956f',
    messagingSenderId: '874965142590',
    projectId: 'titixplorerdb',
    databaseURL: 'https://titixplorerdb-default-rtdb.firebaseio.com',
    storageBucket: 'titixplorerdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsmys8NxtqoJXaSwCiTmIDBQt2sgwq2_8',
    appId: '1:874965142590:ios:c83af183c38360c88a956f',
    messagingSenderId: '874965142590',
    projectId: 'titixplorerdb',
    databaseURL: 'https://titixplorerdb-default-rtdb.firebaseio.com',
    storageBucket: 'titixplorerdb.appspot.com',
    iosClientId: '874965142590-c57ms1m2englqj9pva4q1rqrg1b0qv0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.ttxplorer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsmys8NxtqoJXaSwCiTmIDBQt2sgwq2_8',
    appId: '1:874965142590:ios:c83af183c38360c88a956f',
    messagingSenderId: '874965142590',
    projectId: 'titixplorerdb',
    databaseURL: 'https://titixplorerdb-default-rtdb.firebaseio.com',
    storageBucket: 'titixplorerdb.appspot.com',
    iosClientId: '874965142590-c57ms1m2englqj9pva4q1rqrg1b0qv0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.ttxplorer',
  );
}
